### ISSUE TITLE
Follow Failed Error

### ISSUE THREAD

**Issue by talatkamas96** [TnYtCoder/InstaFans#1]
It gives follow failed error after following some celebrities

**Comment by TnYtCoder** [comment]
__Bro attach screenshot with it. So I can understand it properly__ . I will also update the user list , Ok

**Comment by TnYtCoder** [comment]
> It gives follow failed error after following some celebrities

Hey brother finally I also faced this problem 😂
The problem is the user list & I will surely update 🗿
