### ISSUE TITLE
PIL Error (solved !)

### ISSUE THREAD

**Issue by Auann02** [TnYtCoder/InstaFans#2]
To tendo esse problema: 
como resolvo?
![Screenshot_20230911_230230_Termux](https://github.com/TnYtCoder/InstaFans/assets/111387430/a352a425-79eb-4aad-8bba-c7ba749a5a72
/
![Screenshot_20230911_230504_Termux](https://github.com/TnYtCoder/InstaFans/assets/111387430/e75a6136-b006-49c1-9941-b4605c3e8477)

Fica pedindo para instalar PIL...

**Comment by Auann02** [comment]
> To tendo esse problema: como resolvo? !
![Screenshot_20230911_230827_Termux](https://github.com/TnYtCoder/InstaFans/assets/111387430/57cbd86d-de56-422a-8362-626f8051bfb2)

> 
> Fica pedindo para instalar PIL...

**Comment by Auann02** [comment]
![Uploading Screenshot_20230911_230230_Termux.jpg…]()

**Comment by Auann02** [comment]
![Uploading Screenshot_20230911_230230_Termux.jpg…]()

**Comment by TnYtCoder** [comment]
**I Think You are Connecting Unrelated Things**

For credentials my repository will help you:
https://github.com/TnYtCoder/InstaFans#installation-termux--nethunter

For PIL Error Try These Commands:
```
pip3 check Pillow
```
If It's Output is- `No broken requirements found.`
Then Run:
```
pip3 install Pillow
```

Or if pip3 check command giving any requirements then continue to install the requirements of it 

Thank You ! ❤️

**Comment by Derechte741** [comment]
Hello How can I activate this once I have entered my details?

**Comment by Derechte741** [comment]
Hello, how can I activate this after entering my details?

**Comment by TnYtCoder** [comment]
No, you can use it multiple times but please read warning in README.md

**Comment by nh-zeeshan** [comment]
![Uploading Screenshot_2023-11-27-20-00-29-60.png…]()
Plz solve this problem

**Comment by Trives0** [comment]
Hey can you pls tell me how to fix this error
![Uploading Screenshot_20231202_210428_Termux.jpg…]()

**Comment by bekzodidiye** [comment]
> Yo'q, siz uni bir necha marta ishlatishingiz mumkin, lekin iltimos, ogohlantirishni o'qing README.md

hello, it says the login password is wrong, I entered it correctly

**Comment by TnYtCoder** [comment]
nano credentials.ini

[Then replace your password and username]
Then try it 👍 

If you're facing any other then open issue ❤️

**Comment by users170688** [comment]
Problem username and password
![Screenshot_2024-03-19-05-14-05-327_com termux](https://github.com/TnYtCoder/InstaFans/assets/163020076/95e90451-4f25-4921-a9a1-a785a77c65e8)
![Screenshot_2024-03-19-05-12-05-457_com termux](https://github.com/TnYtCoder/InstaFans/assets/163020076/69f12899-8a82-44e1-b444-a94181a81929)

**Comment by TnYtCoder** [comment]
@users170688 replace username with  your real username and password with your real password.

- EXAMPLE -

--before--
[Instagram Credentials]
username 
password

--after--
[Instagram Credentials]
baby123
spiiderman123

**Comment by users170688** [comment]
I do what you say but I am facing the same mistake again. Please make a few screen notes and show them to me.

**Comment by Saurabh5112** [comment]
Please solve this problem 
![Screenshot_2024-03-27-01-57-17-951_com termux](https://github.com/TnYtCoder/InstaFans/assets/164845078/7da01fbc-880e-496f-bcab-e183c746123f)
![Screenshot_2024-03-27-01-55-42-324_com termux](https://github.com/TnYtCoder/InstaFans/assets/164845078/fa1d0b7c-b14b-48aa-b958-3c20e4c7d315)
![Screenshot_2024-03-27-01-56-17-169_com termux](https://github.com/TnYtCoder/InstaFans/assets/164845078/5163bd36-46e6-441e-b457-be6f4ddbe2b7)
![Screenshot_2024-03-27-01-58-35-797_com termux](https://github.com/TnYtCoder/InstaFans/assets/164845078/55add6ab-45d9-4fbf-95ae-f01c8bd6126c)

**Comment by Saurabh5112** [comment]
> I do what you say but I am facing the same mistake again. Please make a few screen notes and show them to me.

1. Replace
2. Save  ( ctrl + O) 
3. Exit    (ctrl +C) 
 Then, use command to run--
python3 instafans.py
Watch Video 
https://youtu.be/dMkOywpbTUU?si=KYn-MWB3asMzGcjM

**Comment by Saurabh5112** [comment]
> I do what you say but I am facing the same mistake again. Please make a few screen notes and show them to me.

> I do what you say but I am facing the same mistake again. Please make a few screen notes and show them to me.

1. Replace
2. Save  ( ctrl + O) 
3. Exit    (ctrl + X)
 Then, use command to run--
python3 instafans.py
Watch Video 
https://youtu.be/dMkOywpbTUU?si=3Nqxq0NzYklU7fAq

**Comment by Darnet00** [comment]
Parça n vai de jeito nenhum troquei tudo certinho sou mobile tá uma ajuda
