### ISSUE TITLE
Error in Instagrapi

### ISSUE THREAD

**Issue by Jaypolarnoir** [TnYtCoder/InstaFans#6]
Please when I try to run it says ;

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/InstaFans/instafans.py", line 1, in <module>
    import os, sys, requests, time, instagrapi
ModuleNotFoundError: No module named 'instagrapi'

Please I don't know anything on how to fix it please can you teach me how to solve this issue.
![Screenshot_20231213-082803](https://github.com/TnYtCoder/InstaFans/assets/142335623/1378f191-f279-47b9-ab95-d0645fcddbc0)

**Comment by TnYtCoder** [comment]
Yeah sure !

`pip3 check instagrapi`
If any output comes out or requires any package then install it using pip3

`pip3 install instagrapi`

**Comment by Jaypolarnoir** [comment]
Please where should I write the pip3 check Instagrapi?! In the nano file on
line 1 or somewhere else...

**Comment by Jaypolarnoir** [comment]
Pip3 install Instagrapi still the same error shows

**Comment by TnYtCoder** [comment]
**don't add any code or command in that code
Just try these in your terminal
![IMG_20231213_142034](https://github.com/TnYtCoder/InstaFans/assets/115485810/ec86feea-4463-44ff-8597-23825b38af29)

I have installed rich because it was required to run it ! If you're getting other then just install it

**Comment by Jaypolarnoir** [comment]
This is another issue when installing pip3 install Instagrapi

**Comment by TnYtCoder** [comment]
Try all the command I've shown to you ! If you're getting more.. then send me screenshot

**Comment by Jaypolarnoir** [comment]
Ok, I will.

**Comment by Jaypolarnoir** [comment]
I have successfully install rich 12
But when pip3 install Instagrapi this is what it says;

**Comment by TnYtCoder** [comment]
Sent me photo after executing "pip3 check instagrapi"

**Comment by Jaypolarnoir** [comment]
After executing pip3 check Instagrapi it says: No broken requirements found.

**Comment by TnYtCoder** [comment]
Then you're good to go 

pip3 install instagrapi

**Comment by Jaypolarnoir** [comment]
Sorry I can open the script now or run pip3 install Instagrapi

**Comment by Jaypolarnoir** [comment]
So what does that mean authored the thread?!

**Comment by TnYtCoder** [comment]
After running the command you're good to go 
And run 

python3 instafans.py ..

**Comment by Jaypolarnoir** [comment]
After running python3 instafnas.py the same error shows up

**Comment by TnYtCoder** [comment]
Send me ss. Let me see

**Comment by Jaypolarnoir** [comment]
How can I solve the authored thread issue

**Comment by TnYtCoder** [comment]
Just send ss of the error

**Comment by TnYtCoder** [comment]
```
pip3 install PySocks==1.7.1
pip3 install pydantic==2.5.2 
pip3 install pycryptodomex==3.18.0
pip3 install idna
pip3 install Pillow
pip3 install instagrapi
```
Run all of them one by one, it will definitely install you instagrapi

**Comment by TnYtCoder** [comment]
Also this 
```
pip3 install chardet
pip3 install charset-normalizer
pip3 install typing_extensions
pip3 install urllib3
```
I only researched this for you 💀🫡
