### ISSUE TITLE
Attempting Login !! Login Failed !? Please Check Your Username & Password

### ISSUE THREAD

**Issue by users170688** [TnYtCoder/InstaFans#8]
![Screenshot_2024-03-19-05-12-05-457_com termux](https://github.com/TnYtCoder/InstaFans/assets/163020076/864eaae9-7901-4fec-9bc2-a5514ddac309)
![Screenshot_2024-03-19-05-14-05-327_com termux](https://github.com/TnYtCoder/InstaFans/assets/163020076/2ceaf524-33d4-40a2-bd31-ab43aadbeebf)

**Comment by TnYtCoder** [comment]
@users170688 replace username with your real username and password with your real password.

--EXAMPLE--
--before--
[Instagram Credentials]
username
password

--after--
[Instagram Credentials]
baby123
spiiderman123
